name: CI-CD

on:
  push:
    branches:
      - main
      - next
      - ng*
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    name: Build & Test App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          npm ci 

      - name: Test
        run: |
          npm run test

      - name: Build
        run: |
          npm run lib:build:prod
          npm run dev-app:build:prod
